excerpt_separator: ""
markdown: kramdown
url: http://serralvo.co
title: Fabricio Serralvo
email: fabricio.serralvo@gmail.com
author: Fabricio
highlighter: rouge
description: 
paginate: 5
google_analytics: UA-65004285-1
